### ISSUE TITLE
TFE dropdown menu is not working

### ISSUE THREAD

**Issue by Toldservice** [skat/dms-public#117]
Hi 
we have got the access to TFE 14 days ago but we have not being able to enter or create any export documents to test the system due to problems uploading the choises in the dropdown menu.

**Comment by nc-dmc** [comment]
Hello

Please refrain from creating issues on github as this is not the correct support channel. 

Create a case on Toolkit under the DMS Online service or contact TOLDST Service desk, servicedesk@toldst.dk

Sincerely
DMC
