### ISSUE TITLE
Links for documentation not working

### ISSUE THREAD

**Issue by WonderingDane** [skat/dms-public#58]
These 3 links, in the readme file, does not work:
[H7 schema documentation](https://skat.github.io/dms-public/H7%20XSDs/)
[I2 schema documentation](https://skat.github.io/dms-public/I2%20XSDs/)
[Notification schema documentation](https://skat.github.io/dms-public/Notification%20XSDs/)

**Comment by nc-emha** [comment]
Links fixed
